# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-05 12:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=10000)),
                ('created_on', models.DateTimeField(default=datetime.datetime(2019, 4, 5, 12, 52, 5, 75348, tzinfo=utc))),
                ('updated_on', models.DateTimeField(default=datetime.datetime(2019, 4, 5, 12, 52, 5, 75394, tzinfo=utc))),
            ],
        ),
    ]
